name: test_math_operations

on:
  push:
    branches:
      - main  # mainブランチへのpushで実行

jobs:
  test:
    runs-on: ubuntu-latest  # ジョブをUbuntu環境で実行
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]  # 複数のPythonバージョンで実行
    steps:
      - uses: actions/checkout@v3  # リポジトリのコードをチェックアウト
      - name: Set up Python  # Pythonをセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}  # matrixで指定されたPythonバージョンを使用
      - name: Run test_math_operations  # シェルスクリプトの実行
        run: bash -xv ./test_math_operations.bash  # `test_math_operations.bash` を実行

